services:
  redis:
    image: redis/redis-stack:latest
    container_name: redis
    hostname: redis
    ports:
      - 6379:6379
      - 8001:8001
    networks:
      - nextjs_net

  web:
    build: .
    # image: nextjs-docker
    container_name: nextjs-web
    hostname: nextjs-web
    ports:
      - 3000:3000
    environment:
      - REDIS_URL=redis://redis:6379
      - REDIS_AVAILABLE=True
    depends_on:
      - redis
    networks:
      - nextjs_net

networks:
  nextjs_net:
    name: nextjs_net
